import { GIZZIBrand } from "@/runtime/brand/meta"

export const GIZZICopy = {
  header: {
    subagentSession: "Subagent session",
    parent: "Parent",
    previous: "Prev",
    next: "Next",
  },
  sidebar: {
    contextPack: "Context Pack",
    runtime: "LSP Runtime",
    adapters: "Adapters",
    workItems: "Work Items",
    workspaceDelta: "Workspace Delta",
    tokens: "tokens",
    used: "used",
    spent: "spent",
    connected: "Connected",
    disabled: "Disabled",
    needsAuth: "Needs auth",
    needsClientID: "Needs client ID",
    failed: "Failed",
    unknown: "Unknown",
    runtimeDisabled: "LSP runtime adapters are disabled in settings",
    runtimeActivate: "LSP runtime adapters activate as files are read",
    onboardingTitle: "Kernel ready",
    onboardingBodyPrimary: `${GIZZIBrand.product} includes free models so you can start immediately.`,
    onboardingBodySecondary: "Connect from 75+ providers to use Claude, GPT, Gemini, and more.",
    connectProviders: "Connect providers",
    mcpSummary(input: { connected: number; errors: number }) {
      const err = input.errors
      const body = err > 0 ? `, ${err} error${err > 1 ? "s" : ""}` : ""
      return `(${input.connected} active${body})`
    },
  },
  footer: {
    boot: "Boot kernel",
    lawBeacon(input: { count: number }) {
      return `${input.count} Law beacon${input.count > 1 ? "s" : ""}`
    },
    runtime: "LSP",
    adapters: "Adapters",
  },
  prompt: {
    variants: "profiles",
    agents: "runtimes",
    commands: "ops",
    shellExit: "exit shell mode",
    connectProviderToSend: "Connect a provider to send prompts",
    categoryPrompt: "Prompt",
    categorySession: "Session",
    clearPrompt: "Clear prompt",
    submitPrompt: "Submit prompt",
    paste: "Paste",
    interruptSession: "Interrupt session",
    openEditor: "Open editor",
    skills: "Skills",
    stashPrompt: "Stash prompt",
    stashPop: "Stash pop",
    stashList: "Stash list",
  },
  palette: {
    copyShareLink: "Copy share link",
    shareSession: "Share session",
    renameSession: "Rename session",
    jumpToMessage: "Jump to message",
    forkFromMessage: "Fork from message",
    unshareSession: "Unshare session",
    undoPreviousMessage: "Undo previous message",
    redo: "Redo",
    hideSidebar: "Hide sidebar",
    showSidebar: "Show sidebar",
    disableCodeConcealment: "Disable code concealment",
    enableCodeConcealment: "Enable code concealment",
    hideTimestamps: "Hide timestamps",
    showTimestamps: "Show timestamps",
    hideThinking: "Hide thinking",
    showThinking: "Show thinking",
    hideRuntimeTrace: "Hide runtime trace",
    showRuntimeTrace: "Show runtime trace",
    hideReceipts: "Hide receipts",
    showReceipts: "Show receipts",
    hidePreviewCards: "Hide runtime cards",
    showPreviewCards: "Show runtime cards",
    hideLaneHistory: "Hide lane history",
    showLaneHistory: "Show lane history",
    disableRuntimeFocus: "Disable runtime focus mode",
    enableRuntimeFocus: "Enable runtime focus mode",
    hideToolDetails: "Hide tool details",
    showToolDetails: "Show tool details",
    toggleSessionScrollbar: "Toggle session scrollbar",
    hideHeader: "Hide header",
    showHeader: "Show header",
    hideGenericToolOutput: "Hide generic tool output",
    showGenericToolOutput: "Show generic tool output",
    pageUp: "Page up",
    pageDown: "Page down",
    lineUp: "Line up",
    lineDown: "Line down",
    halfPageUp: "Half page up",
    halfPageDown: "Half page down",
    firstMessage: "First message",
    lastMessage: "Last message",
    jumpToLastUserMessage: "Jump to last user message",
    nextMessage: "Next message",
    previousMessage: "Previous message",
    copyLastAssistantMessage: "Copy last assistant message",
    copySessionTranscript: "Copy session transcript",
    exportSessionTranscript: "Export session transcript",
    nextChildSession: "Next child session",
    previousChildSession: "Previous child session",
    goToParentSession: "Go to parent session",
  },
  toast: {
    clipboardCopied: "Copied to clipboard",
    shareUrlCopied: "Share URL copied to clipboard!",
    shareUrlCopyFailed: "Failed to copy URL to clipboard",
    shareSessionFailed: "Failed to share session",
    unsharedSuccess: "Session unshared successfully",
    unsharedFailed: "Failed to unshare session",
    noAssistantMessages: "No assistant messages found",
    noAssistantTextParts: "No text parts found in last assistant message",
    noAssistantTextContent: "No text content found in last assistant message",
    messageCopied: "Message copied to clipboard!",
    messageCopyFailed: "Failed to copy to clipboard",
    transcriptCopied: "Session transcript copied to clipboard!",
    transcriptCopyFailed: "Failed to copy session transcript",
    exported(input: { filename: string }) {
      return `Session exported to ${input.filename}`
    },
    exportFailed: "Failed to export session",
    invalidModelFormat(input: { value: string }) {
      return `Invalid model format: ${input.value}`
    },
    onboardingDismissed: "Getting started guide dismissed",
    compactStarted: "Compacting session context…",
    compactFailed: "Failed to compact context",
    handoffStarted: "Preparing handoff bundle…",
    handoffFailed: "Failed to create handoff",
    connectionLost: "Connection to server lost — retrying",
    connectionRestored: "Connection restored",
    mcpConnectFailed(input: { name: string }) {
      return `MCP adapter "${input.name}" failed to connect`
    },
    sessionRenameFailed: "Failed to rename session",
    sessionRenameSuccess: "Session renamed",
    permissionDenied: "Permission denied — agent will stop",
  },
  model: {
    connectProvider: "Connect a provider",
    noProviderSelected: "No provider selected",
    addFavoriteToUseShortcut: "Add a favorite model to use this shortcut",
    blockedModelFallback: "This model is currently blocked for this account. Switched to a supported default.",
    blockedModelHint: "Unavailable with current account/provider",
  },
  permission: {
    alwaysAllowTitle: "Always allow",
    requiredTitle: "Permission required",
  },
  question: {
    title: "Kernel Question",
    review: "Receipt Preview",
    confirm: "Seal",
    notAnswered: "(pending)",
    selectMultipleSuffix: "(select one or more)",
    keyTab: "tab",
    keySelect: "select",
    keyToggle: "toggle",
    keySubmit: "submit",
    keyConfirm: "confirm",
    keyDismiss: "dismiss",
    customAnswer: "Type your own answer",
  },
  command: {
    connectProvider: "Connect providers",
  },
  dialog: {
    statusTitle: "Kernel Status",
    runtimeSummaryTitle: "Runtime Summary",
    runtimeModel: "Model",
    runtimeProvider: "Provider",
    runtimeBusySessions: "Busy sessions",
    runtimeRetryingSessions: "Retrying",
    runtimeActiveTools: "Active tools",
    runtimeContextTokens: "Context tokens",
    runtimeTotalTokens: "Total tokens",
    runtimeCost: "Turn cost",
    noAdapters: "No adapters connected",
    adapters(input: { count: number }) {
      return `${input.count} Adapters`
    },
    lspServers(input: { count: number }) {
      return `${input.count} LSP Servers`
    },
    noFormatters: "No formatters available",
    formatters(input: { count: number }) {
      return `${input.count} Formatters`
    },
    noPlugins: "No plugins loaded",
    plugins(input: { count: number }) {
      return `${input.count} Plugins`
    },
    connectProvider: "Connect providers",
    viewAllProviders: "View all providers",
    selectModel: "Select runtime model",
    favorite: "Favorite",
    favorites: "Favorites",
    recent: "Recent",
    popularProviders: "Popular providers",
    favoriteTag: "(Favorite)",
    free: "Free",
    mcpDisabled: "Disabled in settings",
    mcpNeedsAuth(input: { name: string }) {
      return `Needs authentication (run: gizzi-code mcp auth ${input.name})`
    },
  },
  dialogs: {
    messageActionsTitle: "Message Actions",
    subagentActionsTitle: "Subagent Actions",
    sessionsTitle: "Sessions",
    stashTitle: "Stash",
    mcpsTitle: "Adapters",
    open: "Open",
    revert: "Revert",
    copy: "Copy",
    fork: "Fork",
    delete: "delete",
    rename: "rename",
    toggle: "toggle",
    messageRevertDescription: "undo messages and file changes",
    messageCopyDescription: "message text to clipboard",
    messageForkDescription: "create a new session",
    subagentOpenDescription: "the subagent's session",
    pressAgainToConfirm(input: { keybind: string }) {
      return `Press ${input.keybind} again to confirm`
    },
    approxLines(input: { count: number }) {
      return `~${input.count} lines`
    },
    loading: "Loading",
    enabled: "Enabled",
    disabled: "Disabled",
    failed: "failed",
    timelineTitle: "Timeline",
    forkFromMessageTitle: "Fork from message",
    skillsTitle: "Skills",
    skillsSearchPlaceholder: "Search skills...",
    skillsCategory: "Skills",
    autocompleteTitle: "Autocomplete",
    themesTitle: "Themes",
    commandsTitle: "Commands",
    suggestedCategory: "Suggested",
    selectAgentTitle: "Select agent",
    agentNative: "native",
    renameSessionTitle: "Rename Session",
    providerSelectAuthMethodTitle: "Select auth method",
    providerConnectTitle: "Connect a provider",
    providerPopularCategory: "Popular",
    providerOtherCategory: "Other",
    providerApiKeyLabel: "API key",
    providerDescriptionGIZZI: "(GIZZIIO ZEN - Recommended)",
    providerDescriptionAnthropic: "(Claude Max or API key)",
    providerDescriptionOpenAI: "(ChatGPT Plus/Pro or API key)",
    providerDescriptionGemini: "(Google AI Studio or Vertex AI key)",
    providerDescriptionBedrock: "(AWS Bedrock - requires AWS credentials)",
    providerDescriptionVertex: "(Google Cloud Vertex AI)",
    providerDescriptionGroq: "(Groq Cloud API key)",
    providerDescriptionOllama: "(Local Ollama instance)",
    providerDescriptionMistral: "(Mistral AI API key)",
    providerDescriptions: {
      gizzi: "(GIZZIIO ZEN - Recommended)",
      anthropic: "(Claude Max or API key)",
      openai: "(ChatGPT Plus/Pro or API key)",
      gemini: "(Google AI Studio or Vertex AI key)",
      bedrock: "(AWS Bedrock - requires AWS credentials)",
      vertex: "(Google Cloud Vertex AI)",
      groq: "(Groq Cloud API key)",
      ollama: "(Local Ollama instance)",
      mistral: "(Mistral AI API key)",
    } as Record<string, string>,
    providerCopiedToClipboard: "Copied to clipboard",
    providerWaitingForAuthorization: "Waiting for authorization...",
    providerCopyAction: "copy",
    providerAuthorizationCodePlaceholder: "Authorization code",
    providerApiKeyPlaceholder: "API key",
    providerInvalidCode: "Invalid code",
    providerGIZZIDescription:
      "GIZZIIO ZEN gives you access to all the best coding models at the cheapest prices with a single API key.",
    providerGIZZIGetKeyPrefix: "Go to",
    providerGIZZIGetKeyUrl: "https://gizzi.io/zen",
    providerGIZZIGetKeySuffix: "to get a key",
  },
  session: {
    createCheckpoint: "Create checkpoint",
    checkpointProviderHint: "Connect a provider to checkpoint this context pack",
    checkpointTitle: "Checkpoint",
    checkpointAuto: "Context Pack updated",
    checkpointManual: "Checkpoint created",
    checkpointFooter: "Receipt Bundle stored in session memory",
    runtimeTrace: "Runtime trace",
    runtimeTraceCaptured: "Runtime trace captured",
    deckRun: "Run",
    deckLive: "LIVE",
    deckThread: "Work thread",
    deckCards: "Task lane",
    deckSealed: "SEALED",
    deckComplete: "COMPLETE",
    composingAnswer: "Composing answer...",
    modeIdle: "Idle",
    modeQueued: "Queued",
    modeConnecting: "Connecting",
    modeHydrating: "Hydrating",
    modeThinking: "Thinking",
    modeWeb: "Web searching",
    modeTools: "Running tools",
    modeResponding: "Drafting",
    modeCompacting: "Compacting",
    hintQueued: "awaiting runtime",
    hintConnecting: "provider handshake",
    hintHydrating: "rehydrating context pack",
    hintPlanning: "decoding WIH",
    hintExecuting: "running tool calls",
    hintResponding: "composing reply",
    hintCompacting: "updating context pack",
    hintWeb: "fetching web context",
    hintTools: "executing tools",
    hintThinking: "reasoning over context",
    queueBadge: "QUEUED",
    interruptLabel: "interrupt",
    interruptAgainLabel: "again to interrupt",
    interruptRunLabel: "interrupt run",
    moreTools(input: { count: number }) {
      return `+${input.count} tools`
    },
    confirmRedoTitle: "Confirm redo",
    confirmRedoBody: "Are you sure you want to restore the reverted messages?",
    interrupted: "interrupted",
    revertedMessages(input: { count: number }) {
      return `${input.count} message reverted`
    },
    restoreHint: "or /redo to restore",
    receiptsHidden: "Receipts hidden",
    queuedLiveHint: "request accepted",
    // Session mount tips (rotate while working)
    tips: [
      "Use @ to mention files and pull context inline",
      "Type / to browse slash commands and skills",
      "Press ! at start of input to run shell commands directly",
      "Press Esc to interrupt a running session",
      "Paste an image file path to attach it as context",
      "Use Ctrl+P to open the command palette",
      "Fork any message to explore alternative paths",
      "Bookmark messages with M for quick navigation",
      "Checkpoints auto-save your session context",
      "Press Y to copy the last code block to clipboard",
    ] as string[],
    // Completion phrases — shown when a run finishes (rotate per session)
    completionPhrases: [
      (t: string) => `Computed for ${t}`,
      (t: string) => `Processed in ${t}`,
      (t: string) => `Run sealed in ${t}`,
      (t: string) => `Committed in ${t} · Allternit`,
      (t: string) => `Kernel returned in ${t}`,
      (t: string) => `Loop closed in ${t} · GIZZIIO`,
      (t: string) => `Dispatched in ${t} · Layer 1`,
      (t: string) => `Receipt captured in ${t}`,
    ] as Array<(t: string) => string>,
  },
  tool: {
    expand: "(ctrl+o to expand)",
    collapse: "(ctrl+o to collapse)",
    shellDefault: "Shell",
    unknown: "unknown",
    viewSubagents: "view subagents",
    noAnswer: "(no answer)",
    matches(input: { count: number }) {
      return `${input.count} ${input.count === 1 ? "match" : "matches"}`
    },
    toolCalls(input: { count: number }) {
      return `${input.count} tool call${input.count === 1 ? "" : "s"}`
    },
    askedQuestions(input: { count: number }) {
      return `Asked ${input.count} question${input.count === 1 ? "" : "s"}`
    },
    labels: {
      write: "Write",
      read: "Read",
      grep: "Grep",
      glob: "Glob",
      list: "List",
      webFetch: "WebFetch",
      exaCodeSearch: "Exa Code Search",
      exaWebSearch: "Exa Web Search",
      task: "Task",
      edit: "Edit",
      patch: "Patch",
      todos: "Work Items",
      questions: "Questions",
      skill: "Skill",
      multiEdit: "MultiEdit",
      wrote: "Wrote",
      deleted: "Deleted",
      created: "Created",
      moved: "Moved",
      patched: "Patched",
      loaded: "Loaded",
    },
    pending: {
      receipt: "Collecting receipt...",
      bash: "Writing command...",
      write: "Preparing write...",
      glob: "Finding files...",
      read: "Reading file...",
      grep: "Searching content...",
      list: "Listing directory...",
      webFetch: "Fetching from the web...",
      codeSearch: "Searching code...",
      webSearch: "Searching web...",
      task: "Delegating...",
      edit: "Preparing edit...",
      patch: "Preparing patch...",
      todos: "Updating work items...",
      question: "Asking questions...",
      skill: "Loading skill...",
      multiEdit: "Preparing edits...",
    },
  },
  agentMode: {
    title: "Agent Control Plane",
    agentsTab: "Agents",
    cronTab: "Cron Jobs",
    runsTab: "Runs",
    noAgents: "No agents configured",
    noCronJobs: "No scheduled jobs",
    noRuns: "No active or recent runs",
  },
} as const
