/**
 * Init Command
 * Production-quality project initialization
 */

import { mkdir, writeFile, access, constants, readFile } from 'fs/promises'
import { join } from 'path'
import { log } from '../cli/utils/log.js'
import { getGlobalConfig } from '../utils/config.js'

export interface InitOptions {
  cwd?: string
  skipGit?: boolean
  template?: string
}

export interface ProjectConfig {
  name: string
  version: string
  description?: string
  type?: 'typescript' | 'javascript' | 'python' | 'rust' | 'go' | 'other'
  settings?: {
    model?: string
    autoUpdate?: boolean
    telemetry?: boolean
  }
}

const DEFAULT_CONFIG: ProjectConfig = {
  name: '',
  version: '0.1.0',
  description: '',
  type: 'typescript',
  settings: {
    model: 'claude-3-sonnet',
    autoUpdate: true,
    telemetry: true,
  },
}

/**
 * Detect project type from files
 */
async function detectProjectType(cwd: string): Promise<ProjectConfig['type']> {
  try {
    // Check for package.json
    await access(join(cwd, 'package.json'), constants.F_OK)
    
    // Check for tsconfig.json
    try {
      await access(join(cwd, 'tsconfig.json'), constants.F_OK)
      return 'typescript'
    } catch {
      return 'javascript'
    }
  } catch {
    // Check for Python
    try {
      await access(join(cwd, 'requirements.txt'), constants.F_OK)
      return 'python'
    } catch {
      try {
        await access(join(cwd, 'pyproject.toml'), constants.F_OK)
        return 'python'
      } catch {
        // Check for Rust
        try {
          await access(join(cwd, 'Cargo.toml'), constants.F_OK)
          return 'rust'
        } catch {
          // Check for Go
          try {
            await access(join(cwd, 'go.mod'), constants.F_OK)
              return 'go'
          } catch {
            return 'other'
          }
        }
      }
    }
  }
}

/**
 * Get project name from directory or package.json
 */
async function getProjectName(cwd: string): Promise<string> {
  // Try package.json
  try {
    const packageJson = await readFile(join(cwd, 'package.json'), 'utf8')
    const pkg = JSON.parse(packageJson)
    if (pkg.name) return pkg.name
  } catch {
    // Fall through
  }
  
  // Use directory name
  const parts = cwd.split('/')
  return parts[parts.length - 1] || 'my-project'
}

/**
 * Create GIZZI.md template
 */
function createGizziMd(config: ProjectConfig): string {
  return `# ${config.name}

## Project Configuration

This project uses Gizzi for AI-assisted development.

### Settings
- **Model**: ${config.settings?.model || 'default'}
- **Auto-update**: ${config.settings?.autoUpdate ? 'enabled' : 'disabled'}
- **Telemetry**: ${config.settings?.telemetry ? 'enabled' : 'disabled'}

### Getting Started

1. Run \`gizzi login\` to authenticate
2. Start a conversation with \`gizzi\`
3. Use \`gizzi help\` for available commands

### Project Structure

Describe your project structure here...

### Custom Instructions

Add any custom instructions for the AI here...

---
*Generated by Gizzi v${getGlobalConfig().version || '0.1.0'}*
`
}

/**
 * Initialize project
 */
export default async function initCommand(options: InitOptions = {}): Promise<void> {
  const cwd = options.cwd || process.cwd()
  
  try {
    log('info', 'Initializing Gizzi project...')
    
    // Check if already initialized
    try {
      await access(join(cwd, '.gizzi', 'config.json'), constants.F_OK)
      log('warn', 'Project already initialized. Use --force to reinitialize.')
      return
    } catch {
      // Not initialized, continue
    }
    
    // Create .gizzi directory
    const gizziDir = join(cwd, '.gizzi')
    await mkdir(gizziDir, { recursive: true })
    await mkdir(join(gizziDir, 'sessions'), { recursive: true })
    await mkdir(join(gizziDir, 'memory'), { recursive: true })
    await mkdir(join(gizziDir, 'cache'), { recursive: true })
    
    // Detect project type
    const projectType = await detectProjectType(cwd)
    const projectName = await getProjectName(cwd)
    
    // Create config
    const config: ProjectConfig = {
      ...DEFAULT_CONFIG,
      name: projectName,
      type: projectType,
    }
    
    // Write config
    await writeFile(
      join(gizziDir, 'config.json'),
      JSON.stringify(config, null, 2)
    )
    
    // Create GIZZI.md if it doesn't exist
    try {
      await access(join(cwd, 'GIZZI.md'), constants.F_OK)
    } catch {
      await writeFile(join(cwd, 'GIZZI.md'), createGizziMd(config))
      log('info', 'Created GIZZI.md')
    }
    
    // Update .gitignore
    if (!options.skipGit) {
      await updateGitignore(cwd)
    }
    
    log('success', `Initialized Gizzi project: ${config.name}`)
    log('info', 'Run `gizzi login` to authenticate')
    
  } catch (error) {
    if (error instanceof Error) {
      log('error', `Initialization failed: ${error.message}`)
    } else {
      log('error', 'Initialization failed with unknown error')
    }
    process.exit(1)
  }
}

/**
 * Update .gitignore to exclude Gizzi files
 */
async function updateGitignore(cwd: string): Promise<void> {
  const gitignorePath = join(cwd, '.gitignore')
  const gizziEntries = [
    '# Gizzi',
    '.gizzi/sessions/',
    '.gizzi/cache/',
    '.gizzi/logs/',
    '',
  ]
  
  try {
    let content = ''
    try {
      content = await readFile(gitignorePath, 'utf8')
    } catch {
      // File doesn't exist
    }
    
    // Check if already has Gizzi entries
    if (content.includes('.gizzi/')) {
      return
    }
    
    // Append Gizzi entries
    const newContent = content + '\n' + gizziEntries.join('\n')
    await writeFile(gitignorePath, newContent.trim() + '\n')
    log('info', 'Updated .gitignore')
  } catch (error) {
    log('warn', 'Could not update .gitignore')
  }
}

export { detectProjectType, getProjectName, createGizziMd }
