import type { Plan } from "./planner";
import { Log } from "@/shared/util/log";
import type { ExecutionReceipt } from "./executor";

export interface VerificationResult {
  passed: boolean;
  reason?: string;
  nextAction: "stop" | "continue" | "replan" | "ask_user";
}

export class Verifier {
  private log = Log.create({ service: "runtime.verifier" });

  constructor(private sessionId: string) {}

  async verify(plan: Plan, receipts: ExecutionReceipt[]): Promise<VerificationResult> {
    this.log.info("Performing empirical verification", { 
      sessionId: this.sessionId, 
      receiptCount: receipts.length 
    });

    // 1. Mandatory Success Check: Did every executed step succeed?
    const fatalFailure = receipts.find(r => !r.success);
    if (fatalFailure) {
      const isDenied = !!fatalFailure.metadata?.denied;
      return {
        passed: false,
        reason: `Step ${fatalFailure.stepId} (${fatalFailure.toolId}) ${isDenied ? 'was denied' : 'failed'}: ${fatalFailure.output}`,
        nextAction: isDenied ? "ask_user" : "replan"
      };
    }

    // 2. Completeness Check: Did we execute all planned steps?
    if (receipts.length < plan.steps.length) {
      return {
        passed: false,
        reason: `Plan execution incomplete: ${receipts.length}/${plan.steps.length} steps executed`,
        nextAction: "continue"
      };
    }

    // 3. Exit Criteria Check: If tests were planned, did they PASS?
    const testStep = plan.steps.find(s => s.toolId === "bash" && s.args.command?.includes("test"));
    if (testStep) {
      const testReceipt = receipts.find(r => r.stepId === testStep.id);
      if (!testReceipt || testReceipt.metadata?.exitCode !== 0) {
        return {
          passed: false,
          reason: "Tests were required but either didn't run or failed",
          nextAction: "replan"
        };
      }
    }

    // 4. Default: If no steps were generated, we need a plan.
    if (plan.steps.length === 0) {
      return {
        passed: false,
        reason: "No actionable steps were generated by the planner",
        nextAction: "replan"
      };
    }

    // 5. Success: All planned steps succeeded and exit criteria (if any) met.
    this.log.info("Verification passed");
    return {
      passed: true,
      nextAction: "stop"
    };
  }
}
